[package]
name = "ddavness/object-event"
description = "A library that allows for custom events to be created for custom OOP implementations. Attempts to reproduce Roblox's syntax as closely as possible while also adding more features."
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["David Duque <david@duqued.net>"]
license = "MIT"
exclude = ["*"]
include = ["init.lua", "LICENSE"]

[dependencies]
